config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask', as: :question

  get 'answer', to: 'questions#answer', as: :answer

  root to: 'questions#ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask

  end

  def answer
    @question = params[:question].downcase

    if @question.blank?
      @question = '🤐'
      @answer = "I can't hear you!"
    elsif @uestion == "i am going to work"
      @answer = 'Great!'
    elsif @question.end_with?("?")
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StupidCoachingRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Roboto:400,400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="question">
  <h1 class="app-title">Stupid Coaching</h1>

  <div class="ask citation-box">
    <p class="citation"><%= @question.capitalize %></p>
    <p class="person-name citation">-You</p>
  </div>

  <div class="coach citation-box">
    <p class="citation"><%= @answer %></p>
    <p class="person-name citation">-Your coach</p>
  </div>

  <%= link_to "Ask a new question", question_path %>
</div>

app/views/questions/ask.html.erb
<div class="question">
  <h1 class="app-title">Stupid Coaching</h1>

  <form action="/answer" style="margin-top: 35px;">
    <div class="input-group mb-3" style="width: 450px;">
      <input type="text" name="question" class="form-control" placeholder="Say something to your coach !">
      <div class="input-group-append">
        <input class="btn btn-primary" type="submit" value="Ask!">
      </div>
    </div>
  </form>
</div>